server:
  port: 0

spring:
  application:
    name: auth-service
  cloud:
    gateway:
      routes:
        auth-service:
          uri: http://auth-service:8080
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/{path}, /${path}
          basePath: /auth-service
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create

service:
  security:
    jwtCookieName: jwt
    jwtRefreshCookieName: jwt-refresh
    jwtSecret: secretKey
    jwtExpirationMs: 60000000
    jwtRefreshExpirationMs: 120000

