server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      routes:
#        auth-service:
#          uri: http://auth-service:8080
#          predicates:
#            - Path=/auth-service/**
#          filters:
#            - RewritePath=/auth-service/{path}, /${path}
#          basePath: /auth-service
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
