server:
  port: 0

spring:
  application:
    name: account-service
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    spingframework: DEBUG
